apiVersion: v1
kind: Pod
metadata:
  name: logs
  labels:
    app: logs
spec:
  containers:
  - name: logs
    image: swarnalathanatarajan/logs:v1
    env:
      - name: RABBITMQ_HOST
        value: rabbitmq
    imagePullPolicy: Always



    
