rest:	
	docker build -t shreekrishnasubburaj/project-rest .
	docker push shreekrishnasubburaj/project-rest:latest

logs:	
	docker build -t shreekrishnasubburaj/project-logs .
	docker push shreekrishnasubburaj/project-logs:latest